env_id: CartPole-v1
batch_size: 256
n_episodes: 1000
warm_up_episodes: 100
gamma: 0.99
train_steps: 5
target_update_freq: 10
learning_rate: 0.0005
replay_buffer_capacity: 10000
units: 64
layers: 3
seed: 0