batch_size: 256
n_episodes: 5000
warm_up_episodes: 100
gamma: 0.99
train_steps: 50
target_update_freq: 10
learning_rate: 0.0005
replay_buffer_capacity: 1000000
units: 256
seed: 42
eval_freq: 50
eval_episodes: 10
final_eval_episodes: 100
